spring:
  zipkin:
    baseUrl: http://localhost:9411/
server:
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
logging:
  config: 'classpath:logback.xml'
management:
  endpoints:
    web.exposure.include: health,info,prometheus
