spring:
  config:
    name: user-service
  application:
    name: user-service
    profiles:
      - dev
server:
  port: 5000
  servlet:
    context-path: /user-api
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka